/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.dibujos1.ui.internal.Dibujos1Activator;

public class Dibujos1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Dibujos1Activator.getInstance().getInjector("org.xtext.example.dibujos1.Dibujos1");
	}

}
