/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.dibujos1.Dibujos1RuntimeModule;
import org.xtext.example.dibujos1.Dibujos1StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Dibujos1IdeSetup extends Dibujos1StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Dibujos1RuntimeModule(), new Dibujos1IdeModule()));
	}
	
}
