/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.ide;


/**
 * Use this class to register ide components.
 */
public class Dibujos1IdeModule extends AbstractDibujos1IdeModule {
}
