/*
 * generated by Xtext 2.38.0
 */
grammar InternalDibujos1;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.example.dibujos1.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.example.dibujos1.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.example.dibujos1.services.Dibujos1GrammarAccess;

}

@parser::members {

 	private Dibujos1GrammarAccess grammarAccess;

    public InternalDibujos1Parser(TokenStream input, Dibujos1GrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Modelo";
   	}

   	@Override
   	protected Dibujos1GrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleModelo
entryRuleModelo returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getModeloRule()); }
	iv_ruleModelo=ruleModelo
	{ $current=$iv_ruleModelo.current; }
	EOF;

// Rule Modelo
ruleModelo returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getModeloAccess().getInstruccionesInstruccionParserRuleCall_0());
			}
			lv_instrucciones_0_0=ruleInstruccion
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getModeloRule());
				}
				add(
					$current,
					"instrucciones",
					lv_instrucciones_0_0,
					"org.xtext.example.dibujos1.Dibujos1.Instruccion");
				afterParserOrEnumRuleCall();
			}
		)
	)*
;

// Entry rule entryRuleInstruccion
entryRuleInstruccion returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInstruccionRule()); }
	iv_ruleInstruccion=ruleInstruccion
	{ $current=$iv_ruleInstruccion.current; }
	EOF;

// Rule Instruccion
ruleInstruccion returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getCirculoParserRuleCall_0());
		}
		this_Circulo_0=ruleCirculo
		{
			$current = $this_Circulo_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getRectanguloParserRuleCall_1());
		}
		this_Rectangulo_1=ruleRectangulo
		{
			$current = $this_Rectangulo_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getLineaParserRuleCall_2());
		}
		this_Linea_2=ruleLinea
		{
			$current = $this_Linea_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getTextoParserRuleCall_3());
		}
		this_Texto_3=ruleTexto
		{
			$current = $this_Texto_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getPuntoParserRuleCall_4());
		}
		this_Punto_4=rulePunto
		{
			$current = $this_Punto_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getColorParserRuleCall_5());
		}
		this_Color_5=ruleColor
		{
			$current = $this_Color_5.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getEstiloParserRuleCall_6());
		}
		this_Estilo_6=ruleEstilo
		{
			$current = $this_Estilo_6.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstruccionAccess().getFuenteParserRuleCall_7());
		}
		this_Fuente_7=ruleFuente
		{
			$current = $this_Fuente_7.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleCirculo
entryRuleCirculo returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCirculoRule()); }
	iv_ruleCirculo=ruleCirculo
	{ $current=$iv_ruleCirculo.current; }
	EOF;

// Rule Circulo
ruleCirculo returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='C'
		{
			newLeafNode(otherlv_0, grammarAccess.getCirculoAccess().getCKeyword_0());
		}
		(
			(
				lv_x_1_0=RULE_INT
				{
					newLeafNode(lv_x_1_0, grammarAccess.getCirculoAccess().getXINTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCirculoRule());
					}
					setWithLastConsumed(
						$current,
						"x",
						lv_x_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y_2_0=RULE_INT
				{
					newLeafNode(lv_y_2_0, grammarAccess.getCirculoAccess().getYINTTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCirculoRule());
					}
					setWithLastConsumed(
						$current,
						"y",
						lv_y_2_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_r_3_0=RULE_INT
				{
					newLeafNode(lv_r_3_0, grammarAccess.getCirculoAccess().getRINTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCirculoRule());
					}
					setWithLastConsumed(
						$current,
						"r",
						lv_r_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleRectangulo
entryRuleRectangulo returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRectanguloRule()); }
	iv_ruleRectangulo=ruleRectangulo
	{ $current=$iv_ruleRectangulo.current; }
	EOF;

// Rule Rectangulo
ruleRectangulo returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='R'
		{
			newLeafNode(otherlv_0, grammarAccess.getRectanguloAccess().getRKeyword_0());
		}
		(
			(
				lv_x1_1_0=RULE_INT
				{
					newLeafNode(lv_x1_1_0, grammarAccess.getRectanguloAccess().getX1INTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"x1",
						lv_x1_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y1_2_0=RULE_INT
				{
					newLeafNode(lv_y1_2_0, grammarAccess.getRectanguloAccess().getY1INTTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"y1",
						lv_y1_2_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_x2_3_0=RULE_INT
				{
					newLeafNode(lv_x2_3_0, grammarAccess.getRectanguloAccess().getX2INTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"x2",
						lv_x2_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y2_4_0=RULE_INT
				{
					newLeafNode(lv_y2_4_0, grammarAccess.getRectanguloAccess().getY2INTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"y2",
						lv_y2_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_x3_5_0=RULE_INT
				{
					newLeafNode(lv_x3_5_0, grammarAccess.getRectanguloAccess().getX3INTTerminalRuleCall_5_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"x3",
						lv_x3_5_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y3_6_0=RULE_INT
				{
					newLeafNode(lv_y3_6_0, grammarAccess.getRectanguloAccess().getY3INTTerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"y3",
						lv_y3_6_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_x4_7_0=RULE_INT
				{
					newLeafNode(lv_x4_7_0, grammarAccess.getRectanguloAccess().getX4INTTerminalRuleCall_7_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"x4",
						lv_x4_7_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y4_8_0=RULE_INT
				{
					newLeafNode(lv_y4_8_0, grammarAccess.getRectanguloAccess().getY4INTTerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRectanguloRule());
					}
					setWithLastConsumed(
						$current,
						"y4",
						lv_y4_8_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleLinea
entryRuleLinea returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLineaRule()); }
	iv_ruleLinea=ruleLinea
	{ $current=$iv_ruleLinea.current; }
	EOF;

// Rule Linea
ruleLinea returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='L'
		{
			newLeafNode(otherlv_0, grammarAccess.getLineaAccess().getLKeyword_0());
		}
		(
			(
				lv_x1_1_0=RULE_INT
				{
					newLeafNode(lv_x1_1_0, grammarAccess.getLineaAccess().getX1INTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLineaRule());
					}
					setWithLastConsumed(
						$current,
						"x1",
						lv_x1_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y1_2_0=RULE_INT
				{
					newLeafNode(lv_y1_2_0, grammarAccess.getLineaAccess().getY1INTTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLineaRule());
					}
					setWithLastConsumed(
						$current,
						"y1",
						lv_y1_2_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_x2_3_0=RULE_INT
				{
					newLeafNode(lv_x2_3_0, grammarAccess.getLineaAccess().getX2INTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLineaRule());
					}
					setWithLastConsumed(
						$current,
						"x2",
						lv_x2_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y2_4_0=RULE_INT
				{
					newLeafNode(lv_y2_4_0, grammarAccess.getLineaAccess().getY2INTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLineaRule());
					}
					setWithLastConsumed(
						$current,
						"y2",
						lv_y2_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleTexto
entryRuleTexto returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTextoRule()); }
	iv_ruleTexto=ruleTexto
	{ $current=$iv_ruleTexto.current; }
	EOF;

// Rule Texto
ruleTexto returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='T'
		{
			newLeafNode(otherlv_0, grammarAccess.getTextoAccess().getTKeyword_0());
		}
		(
			(
				lv_x_1_0=RULE_INT
				{
					newLeafNode(lv_x_1_0, grammarAccess.getTextoAccess().getXINTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTextoRule());
					}
					setWithLastConsumed(
						$current,
						"x",
						lv_x_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y_2_0=RULE_INT
				{
					newLeafNode(lv_y_2_0, grammarAccess.getTextoAccess().getYINTTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTextoRule());
					}
					setWithLastConsumed(
						$current,
						"y",
						lv_y_2_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_texto_3_0=RULE_STRING
				{
					newLeafNode(lv_texto_3_0, grammarAccess.getTextoAccess().getTextoSTRINGTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTextoRule());
					}
					setWithLastConsumed(
						$current,
						"texto",
						lv_texto_3_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRulePunto
entryRulePunto returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPuntoRule()); }
	iv_rulePunto=rulePunto
	{ $current=$iv_rulePunto.current; }
	EOF;

// Rule Punto
rulePunto returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='P'
		{
			newLeafNode(otherlv_0, grammarAccess.getPuntoAccess().getPKeyword_0());
		}
		(
			(
				lv_x_1_0=RULE_INT
				{
					newLeafNode(lv_x_1_0, grammarAccess.getPuntoAccess().getXINTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPuntoRule());
					}
					setWithLastConsumed(
						$current,
						"x",
						lv_x_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				lv_y_2_0=RULE_INT
				{
					newLeafNode(lv_y_2_0, grammarAccess.getPuntoAccess().getYINTTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPuntoRule());
					}
					setWithLastConsumed(
						$current,
						"y",
						lv_y_2_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleColor
entryRuleColor returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getColorRule()); }
	iv_ruleColor=ruleColor
	{ $current=$iv_ruleColor.current; }
	EOF;

// Rule Color
ruleColor returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			otherlv_0='SC'
			{
				newLeafNode(otherlv_0, grammarAccess.getColorAccess().getSCKeyword_0_0());
			}
			    |
			otherlv_1='FC'
			{
				newLeafNode(otherlv_1, grammarAccess.getColorAccess().getFCKeyword_0_1());
			}
			    |
			otherlv_2='BG'
			{
				newLeafNode(otherlv_2, grammarAccess.getColorAccess().getBGKeyword_0_2());
			}
		)
		(
			(
				lv_color_3_0=RULE_HEXCOLOR
				{
					newLeafNode(lv_color_3_0, grammarAccess.getColorAccess().getColorHEXCOLORTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getColorRule());
					}
					setWithLastConsumed(
						$current,
						"color",
						lv_color_3_0,
						"org.xtext.example.dibujos1.Dibujos1.HEXCOLOR");
				}
			)
		)
	)
;

// Entry rule entryRuleEstilo
entryRuleEstilo returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEstiloRule()); }
	iv_ruleEstilo=ruleEstilo
	{ $current=$iv_ruleEstilo.current; }
	EOF;

// Rule Estilo
ruleEstilo returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='SW'
		{
			newLeafNode(otherlv_0, grammarAccess.getEstiloAccess().getSWKeyword_0());
		}
		(
			(
				lv_valor_1_0=RULE_INT
				{
					newLeafNode(lv_valor_1_0, grammarAccess.getEstiloAccess().getValorINTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getEstiloRule());
					}
					setWithLastConsumed(
						$current,
						"valor",
						lv_valor_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleFuente
entryRuleFuente returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getFuenteRule()); }
	iv_ruleFuente=ruleFuente
	{ $current=$iv_ruleFuente.current; }
	EOF;

// Rule Fuente
ruleFuente returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='FS'
		{
			newLeafNode(otherlv_0, grammarAccess.getFuenteAccess().getFSKeyword_0());
		}
		(
			(
				lv_valor_1_0=RULE_INT
				{
					newLeafNode(lv_valor_1_0, grammarAccess.getFuenteAccess().getValorINTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getFuenteRule());
					}
					setWithLastConsumed(
						$current,
						"valor",
						lv_valor_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

RULE_HEXCOLOR : '#' ('A'..'F'|'a'..'f'|'0'..'9')+;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
