/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.dibujos1.dibujos1.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class Dibujos1FactoryImpl extends EFactoryImpl implements Dibujos1Factory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static Dibujos1Factory init()
  {
    try
    {
      Dibujos1Factory theDibujos1Factory = (Dibujos1Factory)EPackage.Registry.INSTANCE.getEFactory(Dibujos1Package.eNS_URI);
      if (theDibujos1Factory != null)
      {
        return theDibujos1Factory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new Dibujos1FactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Dibujos1FactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case Dibujos1Package.MODELO: return createModelo();
      case Dibujos1Package.INSTRUCCION: return createInstruccion();
      case Dibujos1Package.CIRCULO: return createCirculo();
      case Dibujos1Package.RECTANGULO: return createRectangulo();
      case Dibujos1Package.LINEA: return createLinea();
      case Dibujos1Package.TEXTO: return createTexto();
      case Dibujos1Package.PUNTO: return createPunto();
      case Dibujos1Package.COLOR: return createColor();
      case Dibujos1Package.ESTILO: return createEstilo();
      case Dibujos1Package.FUENTE: return createFuente();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Modelo createModelo()
  {
    ModeloImpl modelo = new ModeloImpl();
    return modelo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Instruccion createInstruccion()
  {
    InstruccionImpl instruccion = new InstruccionImpl();
    return instruccion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Circulo createCirculo()
  {
    CirculoImpl circulo = new CirculoImpl();
    return circulo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rectangulo createRectangulo()
  {
    RectanguloImpl rectangulo = new RectanguloImpl();
    return rectangulo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Linea createLinea()
  {
    LineaImpl linea = new LineaImpl();
    return linea;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Texto createTexto()
  {
    TextoImpl texto = new TextoImpl();
    return texto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Punto createPunto()
  {
    PuntoImpl punto = new PuntoImpl();
    return punto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Color createColor()
  {
    ColorImpl color = new ColorImpl();
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Estilo createEstilo()
  {
    EstiloImpl estilo = new EstiloImpl();
    return estilo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fuente createFuente()
  {
    FuenteImpl fuente = new FuenteImpl();
    return fuente;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dibujos1Package getDibujos1Package()
  {
    return (Dibujos1Package)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static Dibujos1Package getPackage()
  {
    return Dibujos1Package.eINSTANCE;
  }

} //Dibujos1FactoryImpl
