/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.dibujos1.dibujos1.Circulo;
import org.xtext.example.dibujos1.dibujos1.Color;
import org.xtext.example.dibujos1.dibujos1.Dibujos1Factory;
import org.xtext.example.dibujos1.dibujos1.Dibujos1Package;
import org.xtext.example.dibujos1.dibujos1.Estilo;
import org.xtext.example.dibujos1.dibujos1.Fuente;
import org.xtext.example.dibujos1.dibujos1.Instruccion;
import org.xtext.example.dibujos1.dibujos1.Linea;
import org.xtext.example.dibujos1.dibujos1.Modelo;
import org.xtext.example.dibujos1.dibujos1.Punto;
import org.xtext.example.dibujos1.dibujos1.Rectangulo;
import org.xtext.example.dibujos1.dibujos1.Texto;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class Dibujos1PackageImpl extends EPackageImpl implements Dibujos1Package
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modeloEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instruccionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass circuloEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rectanguloEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lineaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass textoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass puntoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass colorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass estiloEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fuenteEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#eNS_URI
   * @see #init()
   * @generated
   */
  private Dibujos1PackageImpl()
  {
    super(eNS_URI, Dibujos1Factory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link Dibujos1Package#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static Dibujos1Package init()
  {
    if (isInited) return (Dibujos1Package)EPackage.Registry.INSTANCE.getEPackage(Dibujos1Package.eNS_URI);

    // Obtain or create and register package
    Object registeredDibujos1Package = EPackage.Registry.INSTANCE.get(eNS_URI);
    Dibujos1PackageImpl theDibujos1Package = registeredDibujos1Package instanceof Dibujos1PackageImpl ? (Dibujos1PackageImpl)registeredDibujos1Package : new Dibujos1PackageImpl();

    isInited = true;

    // Create package meta-data objects
    theDibujos1Package.createPackageContents();

    // Initialize created meta-data
    theDibujos1Package.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDibujos1Package.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(Dibujos1Package.eNS_URI, theDibujos1Package);
    return theDibujos1Package;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelo()
  {
    return modeloEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelo_Instrucciones()
  {
    return (EReference)modeloEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstruccion()
  {
    return instruccionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCirculo()
  {
    return circuloEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCirculo_X()
  {
    return (EAttribute)circuloEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCirculo_Y()
  {
    return (EAttribute)circuloEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCirculo_R()
  {
    return (EAttribute)circuloEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRectangulo()
  {
    return rectanguloEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_X1()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_Y1()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_X2()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_Y2()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_X3()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_Y3()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_X4()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRectangulo_Y4()
  {
    return (EAttribute)rectanguloEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLinea()
  {
    return lineaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLinea_X1()
  {
    return (EAttribute)lineaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLinea_Y1()
  {
    return (EAttribute)lineaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLinea_X2()
  {
    return (EAttribute)lineaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLinea_Y2()
  {
    return (EAttribute)lineaEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTexto()
  {
    return textoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTexto_X()
  {
    return (EAttribute)textoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTexto_Y()
  {
    return (EAttribute)textoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTexto_Texto()
  {
    return (EAttribute)textoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPunto()
  {
    return puntoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPunto_X()
  {
    return (EAttribute)puntoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPunto_Y()
  {
    return (EAttribute)puntoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getColor()
  {
    return colorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getColor_Color()
  {
    return (EAttribute)colorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEstilo()
  {
    return estiloEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEstilo_Valor()
  {
    return (EAttribute)estiloEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuente()
  {
    return fuenteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFuente_Valor()
  {
    return (EAttribute)fuenteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dibujos1Factory getDibujos1Factory()
  {
    return (Dibujos1Factory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modeloEClass = createEClass(MODELO);
    createEReference(modeloEClass, MODELO__INSTRUCCIONES);

    instruccionEClass = createEClass(INSTRUCCION);

    circuloEClass = createEClass(CIRCULO);
    createEAttribute(circuloEClass, CIRCULO__X);
    createEAttribute(circuloEClass, CIRCULO__Y);
    createEAttribute(circuloEClass, CIRCULO__R);

    rectanguloEClass = createEClass(RECTANGULO);
    createEAttribute(rectanguloEClass, RECTANGULO__X1);
    createEAttribute(rectanguloEClass, RECTANGULO__Y1);
    createEAttribute(rectanguloEClass, RECTANGULO__X2);
    createEAttribute(rectanguloEClass, RECTANGULO__Y2);
    createEAttribute(rectanguloEClass, RECTANGULO__X3);
    createEAttribute(rectanguloEClass, RECTANGULO__Y3);
    createEAttribute(rectanguloEClass, RECTANGULO__X4);
    createEAttribute(rectanguloEClass, RECTANGULO__Y4);

    lineaEClass = createEClass(LINEA);
    createEAttribute(lineaEClass, LINEA__X1);
    createEAttribute(lineaEClass, LINEA__Y1);
    createEAttribute(lineaEClass, LINEA__X2);
    createEAttribute(lineaEClass, LINEA__Y2);

    textoEClass = createEClass(TEXTO);
    createEAttribute(textoEClass, TEXTO__X);
    createEAttribute(textoEClass, TEXTO__Y);
    createEAttribute(textoEClass, TEXTO__TEXTO);

    puntoEClass = createEClass(PUNTO);
    createEAttribute(puntoEClass, PUNTO__X);
    createEAttribute(puntoEClass, PUNTO__Y);

    colorEClass = createEClass(COLOR);
    createEAttribute(colorEClass, COLOR__COLOR);

    estiloEClass = createEClass(ESTILO);
    createEAttribute(estiloEClass, ESTILO__VALOR);

    fuenteEClass = createEClass(FUENTE);
    createEAttribute(fuenteEClass, FUENTE__VALOR);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    circuloEClass.getESuperTypes().add(this.getInstruccion());
    rectanguloEClass.getESuperTypes().add(this.getInstruccion());
    lineaEClass.getESuperTypes().add(this.getInstruccion());
    textoEClass.getESuperTypes().add(this.getInstruccion());
    puntoEClass.getESuperTypes().add(this.getInstruccion());
    colorEClass.getESuperTypes().add(this.getInstruccion());
    estiloEClass.getESuperTypes().add(this.getInstruccion());
    fuenteEClass.getESuperTypes().add(this.getInstruccion());

    // Initialize classes and features; add operations and parameters
    initEClass(modeloEClass, Modelo.class, "Modelo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModelo_Instrucciones(), this.getInstruccion(), null, "instrucciones", null, 0, -1, Modelo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(instruccionEClass, Instruccion.class, "Instruccion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(circuloEClass, Circulo.class, "Circulo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCirculo_X(), ecorePackage.getEInt(), "x", null, 0, 1, Circulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCirculo_Y(), ecorePackage.getEInt(), "y", null, 0, 1, Circulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCirculo_R(), ecorePackage.getEInt(), "r", null, 0, 1, Circulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rectanguloEClass, Rectangulo.class, "Rectangulo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRectangulo_X1(), ecorePackage.getEInt(), "x1", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRectangulo_Y1(), ecorePackage.getEInt(), "y1", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRectangulo_X2(), ecorePackage.getEInt(), "x2", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRectangulo_Y2(), ecorePackage.getEInt(), "y2", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRectangulo_X3(), ecorePackage.getEInt(), "x3", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRectangulo_Y3(), ecorePackage.getEInt(), "y3", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRectangulo_X4(), ecorePackage.getEInt(), "x4", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRectangulo_Y4(), ecorePackage.getEInt(), "y4", null, 0, 1, Rectangulo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lineaEClass, Linea.class, "Linea", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLinea_X1(), ecorePackage.getEInt(), "x1", null, 0, 1, Linea.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLinea_Y1(), ecorePackage.getEInt(), "y1", null, 0, 1, Linea.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLinea_X2(), ecorePackage.getEInt(), "x2", null, 0, 1, Linea.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLinea_Y2(), ecorePackage.getEInt(), "y2", null, 0, 1, Linea.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(textoEClass, Texto.class, "Texto", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTexto_X(), ecorePackage.getEInt(), "x", null, 0, 1, Texto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTexto_Y(), ecorePackage.getEInt(), "y", null, 0, 1, Texto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTexto_Texto(), ecorePackage.getEString(), "texto", null, 0, 1, Texto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(puntoEClass, Punto.class, "Punto", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPunto_X(), ecorePackage.getEInt(), "x", null, 0, 1, Punto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPunto_Y(), ecorePackage.getEInt(), "y", null, 0, 1, Punto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(colorEClass, Color.class, "Color", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getColor_Color(), ecorePackage.getEString(), "color", null, 0, 1, Color.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(estiloEClass, Estilo.class, "Estilo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEstilo_Valor(), ecorePackage.getEInt(), "valor", null, 0, 1, Estilo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fuenteEClass, Fuente.class, "Fuente", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFuente_Valor(), ecorePackage.getEInt(), "valor", null, 0, 1, Fuente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //Dibujos1PackageImpl
