/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.dibujos1.dibujos1.Dibujos1Package;
import org.xtext.example.dibujos1.dibujos1.Instruccion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Instruccion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InstruccionImpl extends MinimalEObjectImpl.Container implements Instruccion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InstruccionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Dibujos1Package.Literals.INSTRUCCION;
  }

} //InstruccionImpl
