/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.dibujos1.dibujos1.Dibujos1Package;
import org.xtext.example.dibujos1.dibujos1.Instruccion;
import org.xtext.example.dibujos1.dibujos1.Modelo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Modelo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.ModeloImpl#getInstrucciones <em>Instrucciones</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModeloImpl extends MinimalEObjectImpl.Container implements Modelo
{
  /**
   * The cached value of the '{@link #getInstrucciones() <em>Instrucciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstrucciones()
   * @generated
   * @ordered
   */
  protected EList<Instruccion> instrucciones;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModeloImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Dibujos1Package.Literals.MODELO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Instruccion> getInstrucciones()
  {
    if (instrucciones == null)
    {
      instrucciones = new EObjectContainmentEList<Instruccion>(Instruccion.class, this, Dibujos1Package.MODELO__INSTRUCCIONES);
    }
    return instrucciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Dibujos1Package.MODELO__INSTRUCCIONES:
        return ((InternalEList<?>)getInstrucciones()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Dibujos1Package.MODELO__INSTRUCCIONES:
        return getInstrucciones();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Dibujos1Package.MODELO__INSTRUCCIONES:
        getInstrucciones().clear();
        getInstrucciones().addAll((Collection<? extends Instruccion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Dibujos1Package.MODELO__INSTRUCCIONES:
        getInstrucciones().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Dibujos1Package.MODELO__INSTRUCCIONES:
        return instrucciones != null && !instrucciones.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModeloImpl
