/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.dibujos1.dibujos1.Dibujos1Package;
import org.xtext.example.dibujos1.dibujos1.Rectangulo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rectangulo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getX1 <em>X1</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getY1 <em>Y1</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getX2 <em>X2</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getY2 <em>Y2</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getX3 <em>X3</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getY3 <em>Y3</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getX4 <em>X4</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl#getY4 <em>Y4</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RectanguloImpl extends InstruccionImpl implements Rectangulo
{
  /**
   * The default value of the '{@link #getX1() <em>X1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX1()
   * @generated
   * @ordered
   */
  protected static final int X1_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getX1() <em>X1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX1()
   * @generated
   * @ordered
   */
  protected int x1 = X1_EDEFAULT;

  /**
   * The default value of the '{@link #getY1() <em>Y1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY1()
   * @generated
   * @ordered
   */
  protected static final int Y1_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getY1() <em>Y1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY1()
   * @generated
   * @ordered
   */
  protected int y1 = Y1_EDEFAULT;

  /**
   * The default value of the '{@link #getX2() <em>X2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX2()
   * @generated
   * @ordered
   */
  protected static final int X2_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getX2() <em>X2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX2()
   * @generated
   * @ordered
   */
  protected int x2 = X2_EDEFAULT;

  /**
   * The default value of the '{@link #getY2() <em>Y2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY2()
   * @generated
   * @ordered
   */
  protected static final int Y2_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getY2() <em>Y2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY2()
   * @generated
   * @ordered
   */
  protected int y2 = Y2_EDEFAULT;

  /**
   * The default value of the '{@link #getX3() <em>X3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX3()
   * @generated
   * @ordered
   */
  protected static final int X3_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getX3() <em>X3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX3()
   * @generated
   * @ordered
   */
  protected int x3 = X3_EDEFAULT;

  /**
   * The default value of the '{@link #getY3() <em>Y3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY3()
   * @generated
   * @ordered
   */
  protected static final int Y3_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getY3() <em>Y3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY3()
   * @generated
   * @ordered
   */
  protected int y3 = Y3_EDEFAULT;

  /**
   * The default value of the '{@link #getX4() <em>X4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX4()
   * @generated
   * @ordered
   */
  protected static final int X4_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getX4() <em>X4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX4()
   * @generated
   * @ordered
   */
  protected int x4 = X4_EDEFAULT;

  /**
   * The default value of the '{@link #getY4() <em>Y4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY4()
   * @generated
   * @ordered
   */
  protected static final int Y4_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getY4() <em>Y4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY4()
   * @generated
   * @ordered
   */
  protected int y4 = Y4_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RectanguloImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Dibujos1Package.Literals.RECTANGULO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getX1()
  {
    return x1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setX1(int newX1)
  {
    int oldX1 = x1;
    x1 = newX1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__X1, oldX1, x1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getY1()
  {
    return y1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setY1(int newY1)
  {
    int oldY1 = y1;
    y1 = newY1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__Y1, oldY1, y1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getX2()
  {
    return x2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setX2(int newX2)
  {
    int oldX2 = x2;
    x2 = newX2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__X2, oldX2, x2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getY2()
  {
    return y2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setY2(int newY2)
  {
    int oldY2 = y2;
    y2 = newY2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__Y2, oldY2, y2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getX3()
  {
    return x3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setX3(int newX3)
  {
    int oldX3 = x3;
    x3 = newX3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__X3, oldX3, x3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getY3()
  {
    return y3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setY3(int newY3)
  {
    int oldY3 = y3;
    y3 = newY3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__Y3, oldY3, y3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getX4()
  {
    return x4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setX4(int newX4)
  {
    int oldX4 = x4;
    x4 = newX4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__X4, oldX4, x4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getY4()
  {
    return y4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setY4(int newY4)
  {
    int oldY4 = y4;
    y4 = newY4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.RECTANGULO__Y4, oldY4, y4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Dibujos1Package.RECTANGULO__X1:
        return getX1();
      case Dibujos1Package.RECTANGULO__Y1:
        return getY1();
      case Dibujos1Package.RECTANGULO__X2:
        return getX2();
      case Dibujos1Package.RECTANGULO__Y2:
        return getY2();
      case Dibujos1Package.RECTANGULO__X3:
        return getX3();
      case Dibujos1Package.RECTANGULO__Y3:
        return getY3();
      case Dibujos1Package.RECTANGULO__X4:
        return getX4();
      case Dibujos1Package.RECTANGULO__Y4:
        return getY4();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Dibujos1Package.RECTANGULO__X1:
        setX1((Integer)newValue);
        return;
      case Dibujos1Package.RECTANGULO__Y1:
        setY1((Integer)newValue);
        return;
      case Dibujos1Package.RECTANGULO__X2:
        setX2((Integer)newValue);
        return;
      case Dibujos1Package.RECTANGULO__Y2:
        setY2((Integer)newValue);
        return;
      case Dibujos1Package.RECTANGULO__X3:
        setX3((Integer)newValue);
        return;
      case Dibujos1Package.RECTANGULO__Y3:
        setY3((Integer)newValue);
        return;
      case Dibujos1Package.RECTANGULO__X4:
        setX4((Integer)newValue);
        return;
      case Dibujos1Package.RECTANGULO__Y4:
        setY4((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Dibujos1Package.RECTANGULO__X1:
        setX1(X1_EDEFAULT);
        return;
      case Dibujos1Package.RECTANGULO__Y1:
        setY1(Y1_EDEFAULT);
        return;
      case Dibujos1Package.RECTANGULO__X2:
        setX2(X2_EDEFAULT);
        return;
      case Dibujos1Package.RECTANGULO__Y2:
        setY2(Y2_EDEFAULT);
        return;
      case Dibujos1Package.RECTANGULO__X3:
        setX3(X3_EDEFAULT);
        return;
      case Dibujos1Package.RECTANGULO__Y3:
        setY3(Y3_EDEFAULT);
        return;
      case Dibujos1Package.RECTANGULO__X4:
        setX4(X4_EDEFAULT);
        return;
      case Dibujos1Package.RECTANGULO__Y4:
        setY4(Y4_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Dibujos1Package.RECTANGULO__X1:
        return x1 != X1_EDEFAULT;
      case Dibujos1Package.RECTANGULO__Y1:
        return y1 != Y1_EDEFAULT;
      case Dibujos1Package.RECTANGULO__X2:
        return x2 != X2_EDEFAULT;
      case Dibujos1Package.RECTANGULO__Y2:
        return y2 != Y2_EDEFAULT;
      case Dibujos1Package.RECTANGULO__X3:
        return x3 != X3_EDEFAULT;
      case Dibujos1Package.RECTANGULO__Y3:
        return y3 != Y3_EDEFAULT;
      case Dibujos1Package.RECTANGULO__X4:
        return x4 != X4_EDEFAULT;
      case Dibujos1Package.RECTANGULO__Y4:
        return y4 != Y4_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (x1: ");
    result.append(x1);
    result.append(", y1: ");
    result.append(y1);
    result.append(", x2: ");
    result.append(x2);
    result.append(", y2: ");
    result.append(y2);
    result.append(", x3: ");
    result.append(x3);
    result.append(", y3: ");
    result.append(y3);
    result.append(", x4: ");
    result.append(x4);
    result.append(", y4: ");
    result.append(y4);
    result.append(')');
    return result.toString();
  }

} //RectanguloImpl
