/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.dibujos1.dibujos1.Dibujos1Package;
import org.xtext.example.dibujos1.dibujos1.Texto;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Texto</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.TextoImpl#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.TextoImpl#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.impl.TextoImpl#getTexto <em>Texto</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TextoImpl extends InstruccionImpl implements Texto
{
  /**
   * The default value of the '{@link #getX() <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX()
   * @generated
   * @ordered
   */
  protected static final int X_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getX() <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX()
   * @generated
   * @ordered
   */
  protected int x = X_EDEFAULT;

  /**
   * The default value of the '{@link #getY() <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY()
   * @generated
   * @ordered
   */
  protected static final int Y_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getY() <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY()
   * @generated
   * @ordered
   */
  protected int y = Y_EDEFAULT;

  /**
   * The default value of the '{@link #getTexto() <em>Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTexto()
   * @generated
   * @ordered
   */
  protected static final String TEXTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTexto() <em>Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTexto()
   * @generated
   * @ordered
   */
  protected String texto = TEXTO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TextoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Dibujos1Package.Literals.TEXTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getX()
  {
    return x;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setX(int newX)
  {
    int oldX = x;
    x = newX;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.TEXTO__X, oldX, x));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getY()
  {
    return y;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setY(int newY)
  {
    int oldY = y;
    y = newY;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.TEXTO__Y, oldY, y));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTexto()
  {
    return texto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTexto(String newTexto)
  {
    String oldTexto = texto;
    texto = newTexto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Dibujos1Package.TEXTO__TEXTO, oldTexto, texto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Dibujos1Package.TEXTO__X:
        return getX();
      case Dibujos1Package.TEXTO__Y:
        return getY();
      case Dibujos1Package.TEXTO__TEXTO:
        return getTexto();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Dibujos1Package.TEXTO__X:
        setX((Integer)newValue);
        return;
      case Dibujos1Package.TEXTO__Y:
        setY((Integer)newValue);
        return;
      case Dibujos1Package.TEXTO__TEXTO:
        setTexto((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Dibujos1Package.TEXTO__X:
        setX(X_EDEFAULT);
        return;
      case Dibujos1Package.TEXTO__Y:
        setY(Y_EDEFAULT);
        return;
      case Dibujos1Package.TEXTO__TEXTO:
        setTexto(TEXTO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Dibujos1Package.TEXTO__X:
        return x != X_EDEFAULT;
      case Dibujos1Package.TEXTO__Y:
        return y != Y_EDEFAULT;
      case Dibujos1Package.TEXTO__TEXTO:
        return TEXTO_EDEFAULT == null ? texto != null : !TEXTO_EDEFAULT.equals(texto);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (x: ");
    result.append(x);
    result.append(", y: ");
    result.append(y);
    result.append(", texto: ");
    result.append(texto);
    result.append(')');
    return result.toString();
  }

} //TextoImpl
