/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDibujos1Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.dibujos1.dibujos1.Dibujos1Package.eINSTANCE);
		return result;
	}
}
