/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.dibujos1.ide.contentassist.antlr.internal.InternalDibujos1Parser;
import org.xtext.example.dibujos1.services.Dibujos1GrammarAccess;

public class Dibujos1Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(Dibujos1GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, Dibujos1GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstruccionAccess().getAlternatives(), "rule__Instruccion__Alternatives");
			builder.put(grammarAccess.getColorAccess().getAlternatives_0(), "rule__Color__Alternatives_0");
			builder.put(grammarAccess.getCirculoAccess().getGroup(), "rule__Circulo__Group__0");
			builder.put(grammarAccess.getRectanguloAccess().getGroup(), "rule__Rectangulo__Group__0");
			builder.put(grammarAccess.getLineaAccess().getGroup(), "rule__Linea__Group__0");
			builder.put(grammarAccess.getTextoAccess().getGroup(), "rule__Texto__Group__0");
			builder.put(grammarAccess.getPuntoAccess().getGroup(), "rule__Punto__Group__0");
			builder.put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
			builder.put(grammarAccess.getEstiloAccess().getGroup(), "rule__Estilo__Group__0");
			builder.put(grammarAccess.getFuenteAccess().getGroup(), "rule__Fuente__Group__0");
			builder.put(grammarAccess.getModeloAccess().getInstruccionesAssignment(), "rule__Modelo__InstruccionesAssignment");
			builder.put(grammarAccess.getCirculoAccess().getXAssignment_1(), "rule__Circulo__XAssignment_1");
			builder.put(grammarAccess.getCirculoAccess().getYAssignment_2(), "rule__Circulo__YAssignment_2");
			builder.put(grammarAccess.getCirculoAccess().getRAssignment_3(), "rule__Circulo__RAssignment_3");
			builder.put(grammarAccess.getRectanguloAccess().getX1Assignment_1(), "rule__Rectangulo__X1Assignment_1");
			builder.put(grammarAccess.getRectanguloAccess().getY1Assignment_2(), "rule__Rectangulo__Y1Assignment_2");
			builder.put(grammarAccess.getRectanguloAccess().getX2Assignment_3(), "rule__Rectangulo__X2Assignment_3");
			builder.put(grammarAccess.getRectanguloAccess().getY2Assignment_4(), "rule__Rectangulo__Y2Assignment_4");
			builder.put(grammarAccess.getRectanguloAccess().getX3Assignment_5(), "rule__Rectangulo__X3Assignment_5");
			builder.put(grammarAccess.getRectanguloAccess().getY3Assignment_6(), "rule__Rectangulo__Y3Assignment_6");
			builder.put(grammarAccess.getRectanguloAccess().getX4Assignment_7(), "rule__Rectangulo__X4Assignment_7");
			builder.put(grammarAccess.getRectanguloAccess().getY4Assignment_8(), "rule__Rectangulo__Y4Assignment_8");
			builder.put(grammarAccess.getLineaAccess().getX1Assignment_1(), "rule__Linea__X1Assignment_1");
			builder.put(grammarAccess.getLineaAccess().getY1Assignment_2(), "rule__Linea__Y1Assignment_2");
			builder.put(grammarAccess.getLineaAccess().getX2Assignment_3(), "rule__Linea__X2Assignment_3");
			builder.put(grammarAccess.getLineaAccess().getY2Assignment_4(), "rule__Linea__Y2Assignment_4");
			builder.put(grammarAccess.getTextoAccess().getXAssignment_1(), "rule__Texto__XAssignment_1");
			builder.put(grammarAccess.getTextoAccess().getYAssignment_2(), "rule__Texto__YAssignment_2");
			builder.put(grammarAccess.getTextoAccess().getTextoAssignment_3(), "rule__Texto__TextoAssignment_3");
			builder.put(grammarAccess.getPuntoAccess().getXAssignment_1(), "rule__Punto__XAssignment_1");
			builder.put(grammarAccess.getPuntoAccess().getYAssignment_2(), "rule__Punto__YAssignment_2");
			builder.put(grammarAccess.getColorAccess().getColorAssignment_1(), "rule__Color__ColorAssignment_1");
			builder.put(grammarAccess.getEstiloAccess().getValorAssignment_1(), "rule__Estilo__ValorAssignment_1");
			builder.put(grammarAccess.getFuenteAccess().getValorAssignment_1(), "rule__Fuente__ValorAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private Dibujos1GrammarAccess grammarAccess;

	@Override
	protected InternalDibujos1Parser createParser() {
		InternalDibujos1Parser result = new InternalDibujos1Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Dibujos1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Dibujos1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
