/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.dibujos1.ui.internal.Dibujos1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Dibujos1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Dibujos1Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Dibujos1Activator activator = Dibujos1Activator.getInstance();
		return activator != null ? activator.getInjector(Dibujos1Activator.ORG_XTEXT_EXAMPLE_DIBUJOS1_DIBUJOS1) : null;
	}

}
