/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Dibujos1UiModule extends AbstractDibujos1UiModule {

	public Dibujos1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
