/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Dibujos1StandaloneSetup extends Dibujos1StandaloneSetupGenerated {

	public static void doSetup() {
		new Dibujos1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
