/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class Dibujos1GrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModeloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Modelo");
		private final Assignment cInstruccionesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cInstruccionesInstruccionParserRuleCall_0 = (RuleCall)cInstruccionesAssignment.eContents().get(0);
		
		//Modelo:
		//    instrucciones+=Instruccion*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//instrucciones+=Instruccion*
		public Assignment getInstruccionesAssignment() { return cInstruccionesAssignment; }
		
		//Instruccion
		public RuleCall getInstruccionesInstruccionParserRuleCall_0() { return cInstruccionesInstruccionParserRuleCall_0; }
	}
	public class InstruccionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Instruccion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCirculoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRectanguloParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLineaParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cTextoParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPuntoParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cColorParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cEstiloParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cFuenteParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Instruccion:
		//      Circulo
		//    | Rectangulo
		//    | Linea
		//    | Texto
		//    | Punto
		//    | Color
		//    | Estilo
		//    | Fuente
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  Circulo
		//| Rectangulo
		//| Linea
		//| Texto
		//| Punto
		//| Color
		//| Estilo
		//| Fuente
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Circulo
		public RuleCall getCirculoParserRuleCall_0() { return cCirculoParserRuleCall_0; }
		
		//Rectangulo
		public RuleCall getRectanguloParserRuleCall_1() { return cRectanguloParserRuleCall_1; }
		
		//Linea
		public RuleCall getLineaParserRuleCall_2() { return cLineaParserRuleCall_2; }
		
		//Texto
		public RuleCall getTextoParserRuleCall_3() { return cTextoParserRuleCall_3; }
		
		//Punto
		public RuleCall getPuntoParserRuleCall_4() { return cPuntoParserRuleCall_4; }
		
		//Color
		public RuleCall getColorParserRuleCall_5() { return cColorParserRuleCall_5; }
		
		//Estilo
		public RuleCall getEstiloParserRuleCall_6() { return cEstiloParserRuleCall_6; }
		
		//Fuente
		public RuleCall getFuenteParserRuleCall_7() { return cFuenteParserRuleCall_7; }
	}
	public class CirculoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Circulo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cXINTTerminalRuleCall_1_0 = (RuleCall)cXAssignment_1.eContents().get(0);
		private final Assignment cYAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cYINTTerminalRuleCall_2_0 = (RuleCall)cYAssignment_2.eContents().get(0);
		private final Assignment cRAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRINTTerminalRuleCall_3_0 = (RuleCall)cRAssignment_3.eContents().get(0);
		
		//Circulo:     'C' x=INT y=INT r=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'C' x=INT y=INT r=INT
		public Group getGroup() { return cGroup; }
		
		//'C'
		public Keyword getCKeyword_0() { return cCKeyword_0; }
		
		//x=INT
		public Assignment getXAssignment_1() { return cXAssignment_1; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_1_0() { return cXINTTerminalRuleCall_1_0; }
		
		//y=INT
		public Assignment getYAssignment_2() { return cYAssignment_2; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_2_0() { return cYINTTerminalRuleCall_2_0; }
		
		//r=INT
		public Assignment getRAssignment_3() { return cRAssignment_3; }
		
		//INT
		public RuleCall getRINTTerminalRuleCall_3_0() { return cRINTTerminalRuleCall_3_0; }
	}
	public class RectanguloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Rectangulo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cX1Assignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cX1INTTerminalRuleCall_1_0 = (RuleCall)cX1Assignment_1.eContents().get(0);
		private final Assignment cY1Assignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cY1INTTerminalRuleCall_2_0 = (RuleCall)cY1Assignment_2.eContents().get(0);
		private final Assignment cX2Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cX2INTTerminalRuleCall_3_0 = (RuleCall)cX2Assignment_3.eContents().get(0);
		private final Assignment cY2Assignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cY2INTTerminalRuleCall_4_0 = (RuleCall)cY2Assignment_4.eContents().get(0);
		private final Assignment cX3Assignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cX3INTTerminalRuleCall_5_0 = (RuleCall)cX3Assignment_5.eContents().get(0);
		private final Assignment cY3Assignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cY3INTTerminalRuleCall_6_0 = (RuleCall)cY3Assignment_6.eContents().get(0);
		private final Assignment cX4Assignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cX4INTTerminalRuleCall_7_0 = (RuleCall)cX4Assignment_7.eContents().get(0);
		private final Assignment cY4Assignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cY4INTTerminalRuleCall_8_0 = (RuleCall)cY4Assignment_8.eContents().get(0);
		
		//Rectangulo:  'R' x1=INT y1=INT x2=INT y2=INT x3=INT y3=INT x4=INT y4=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'R' x1=INT y1=INT x2=INT y2=INT x3=INT y3=INT x4=INT y4=INT
		public Group getGroup() { return cGroup; }
		
		//'R'
		public Keyword getRKeyword_0() { return cRKeyword_0; }
		
		//x1=INT
		public Assignment getX1Assignment_1() { return cX1Assignment_1; }
		
		//INT
		public RuleCall getX1INTTerminalRuleCall_1_0() { return cX1INTTerminalRuleCall_1_0; }
		
		//y1=INT
		public Assignment getY1Assignment_2() { return cY1Assignment_2; }
		
		//INT
		public RuleCall getY1INTTerminalRuleCall_2_0() { return cY1INTTerminalRuleCall_2_0; }
		
		//x2=INT
		public Assignment getX2Assignment_3() { return cX2Assignment_3; }
		
		//INT
		public RuleCall getX2INTTerminalRuleCall_3_0() { return cX2INTTerminalRuleCall_3_0; }
		
		//y2=INT
		public Assignment getY2Assignment_4() { return cY2Assignment_4; }
		
		//INT
		public RuleCall getY2INTTerminalRuleCall_4_0() { return cY2INTTerminalRuleCall_4_0; }
		
		//x3=INT
		public Assignment getX3Assignment_5() { return cX3Assignment_5; }
		
		//INT
		public RuleCall getX3INTTerminalRuleCall_5_0() { return cX3INTTerminalRuleCall_5_0; }
		
		//y3=INT
		public Assignment getY3Assignment_6() { return cY3Assignment_6; }
		
		//INT
		public RuleCall getY3INTTerminalRuleCall_6_0() { return cY3INTTerminalRuleCall_6_0; }
		
		//x4=INT
		public Assignment getX4Assignment_7() { return cX4Assignment_7; }
		
		//INT
		public RuleCall getX4INTTerminalRuleCall_7_0() { return cX4INTTerminalRuleCall_7_0; }
		
		//y4=INT
		public Assignment getY4Assignment_8() { return cY4Assignment_8; }
		
		//INT
		public RuleCall getY4INTTerminalRuleCall_8_0() { return cY4INTTerminalRuleCall_8_0; }
	}
	public class LineaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Linea");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cX1Assignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cX1INTTerminalRuleCall_1_0 = (RuleCall)cX1Assignment_1.eContents().get(0);
		private final Assignment cY1Assignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cY1INTTerminalRuleCall_2_0 = (RuleCall)cY1Assignment_2.eContents().get(0);
		private final Assignment cX2Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cX2INTTerminalRuleCall_3_0 = (RuleCall)cX2Assignment_3.eContents().get(0);
		private final Assignment cY2Assignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cY2INTTerminalRuleCall_4_0 = (RuleCall)cY2Assignment_4.eContents().get(0);
		
		//Linea:       'L' x1=INT y1=INT x2=INT y2=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'L' x1=INT y1=INT x2=INT y2=INT
		public Group getGroup() { return cGroup; }
		
		//'L'
		public Keyword getLKeyword_0() { return cLKeyword_0; }
		
		//x1=INT
		public Assignment getX1Assignment_1() { return cX1Assignment_1; }
		
		//INT
		public RuleCall getX1INTTerminalRuleCall_1_0() { return cX1INTTerminalRuleCall_1_0; }
		
		//y1=INT
		public Assignment getY1Assignment_2() { return cY1Assignment_2; }
		
		//INT
		public RuleCall getY1INTTerminalRuleCall_2_0() { return cY1INTTerminalRuleCall_2_0; }
		
		//x2=INT
		public Assignment getX2Assignment_3() { return cX2Assignment_3; }
		
		//INT
		public RuleCall getX2INTTerminalRuleCall_3_0() { return cX2INTTerminalRuleCall_3_0; }
		
		//y2=INT
		public Assignment getY2Assignment_4() { return cY2Assignment_4; }
		
		//INT
		public RuleCall getY2INTTerminalRuleCall_4_0() { return cY2INTTerminalRuleCall_4_0; }
	}
	public class TextoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Texto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cXINTTerminalRuleCall_1_0 = (RuleCall)cXAssignment_1.eContents().get(0);
		private final Assignment cYAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cYINTTerminalRuleCall_2_0 = (RuleCall)cYAssignment_2.eContents().get(0);
		private final Assignment cTextoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextoSTRINGTerminalRuleCall_3_0 = (RuleCall)cTextoAssignment_3.eContents().get(0);
		
		//Texto:       'T' x=INT y=INT texto=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'T' x=INT y=INT texto=STRING
		public Group getGroup() { return cGroup; }
		
		//'T'
		public Keyword getTKeyword_0() { return cTKeyword_0; }
		
		//x=INT
		public Assignment getXAssignment_1() { return cXAssignment_1; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_1_0() { return cXINTTerminalRuleCall_1_0; }
		
		//y=INT
		public Assignment getYAssignment_2() { return cYAssignment_2; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_2_0() { return cYINTTerminalRuleCall_2_0; }
		
		//texto=STRING
		public Assignment getTextoAssignment_3() { return cTextoAssignment_3; }
		
		//STRING
		public RuleCall getTextoSTRINGTerminalRuleCall_3_0() { return cTextoSTRINGTerminalRuleCall_3_0; }
	}
	public class PuntoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Punto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cXINTTerminalRuleCall_1_0 = (RuleCall)cXAssignment_1.eContents().get(0);
		private final Assignment cYAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cYINTTerminalRuleCall_2_0 = (RuleCall)cYAssignment_2.eContents().get(0);
		
		//Punto:       'P' x=INT y=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'P' x=INT y=INT
		public Group getGroup() { return cGroup; }
		
		//'P'
		public Keyword getPKeyword_0() { return cPKeyword_0; }
		
		//x=INT
		public Assignment getXAssignment_1() { return cXAssignment_1; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_1_0() { return cXINTTerminalRuleCall_1_0; }
		
		//y=INT
		public Assignment getYAssignment_2() { return cYAssignment_2; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_2_0() { return cYINTTerminalRuleCall_2_0; }
	}
	public class ColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Color");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cSCKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cFCKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cBGKeyword_0_2 = (Keyword)cAlternatives_0.eContents().get(2);
		private final Assignment cColorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cColorHEXCOLORTerminalRuleCall_1_0 = (RuleCall)cColorAssignment_1.eContents().get(0);
		
		//Color:       ('SC' | 'FC' | 'BG') color=HEXCOLOR;
		@Override public ParserRule getRule() { return rule; }
		
		//('SC' | 'FC' | 'BG') color=HEXCOLOR
		public Group getGroup() { return cGroup; }
		
		//('SC' | 'FC' | 'BG')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'SC'
		public Keyword getSCKeyword_0_0() { return cSCKeyword_0_0; }
		
		//'FC'
		public Keyword getFCKeyword_0_1() { return cFCKeyword_0_1; }
		
		//'BG'
		public Keyword getBGKeyword_0_2() { return cBGKeyword_0_2; }
		
		//color=HEXCOLOR
		public Assignment getColorAssignment_1() { return cColorAssignment_1; }
		
		//HEXCOLOR
		public RuleCall getColorHEXCOLORTerminalRuleCall_1_0() { return cColorHEXCOLORTerminalRuleCall_1_0; }
	}
	public class EstiloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Estilo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSWKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValorINTTerminalRuleCall_1_0 = (RuleCall)cValorAssignment_1.eContents().get(0);
		
		//Estilo:      'SW' valor=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'SW' valor=INT
		public Group getGroup() { return cGroup; }
		
		//'SW'
		public Keyword getSWKeyword_0() { return cSWKeyword_0; }
		
		//valor=INT
		public Assignment getValorAssignment_1() { return cValorAssignment_1; }
		
		//INT
		public RuleCall getValorINTTerminalRuleCall_1_0() { return cValorINTTerminalRuleCall_1_0; }
	}
	public class FuenteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.Fuente");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValorINTTerminalRuleCall_1_0 = (RuleCall)cValorAssignment_1.eContents().get(0);
		
		//Fuente:      'FS' valor=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'FS' valor=INT
		public Group getGroup() { return cGroup; }
		
		//'FS'
		public Keyword getFSKeyword_0() { return cFSKeyword_0; }
		
		//valor=INT
		public Assignment getValorAssignment_1() { return cValorAssignment_1; }
		
		//INT
		public RuleCall getValorINTTerminalRuleCall_1_0() { return cValorINTTerminalRuleCall_1_0; }
	}
	
	
	private final ModeloElements pModelo;
	private final InstruccionElements pInstruccion;
	private final CirculoElements pCirculo;
	private final RectanguloElements pRectangulo;
	private final LineaElements pLinea;
	private final TextoElements pTexto;
	private final PuntoElements pPunto;
	private final ColorElements pColor;
	private final EstiloElements pEstilo;
	private final FuenteElements pFuente;
	private final TerminalRule tHEXCOLOR;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public Dibujos1GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModelo = new ModeloElements();
		this.pInstruccion = new InstruccionElements();
		this.pCirculo = new CirculoElements();
		this.pRectangulo = new RectanguloElements();
		this.pLinea = new LineaElements();
		this.pTexto = new TextoElements();
		this.pPunto = new PuntoElements();
		this.pColor = new ColorElements();
		this.pEstilo = new EstiloElements();
		this.pFuente = new FuenteElements();
		this.tHEXCOLOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.dibujos1.Dibujos1.HEXCOLOR");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.dibujos1.Dibujos1".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Modelo:
	//    instrucciones+=Instruccion*
	//;
	public ModeloElements getModeloAccess() {
		return pModelo;
	}
	
	public ParserRule getModeloRule() {
		return getModeloAccess().getRule();
	}
	
	//Instruccion:
	//      Circulo
	//    | Rectangulo
	//    | Linea
	//    | Texto
	//    | Punto
	//    | Color
	//    | Estilo
	//    | Fuente
	//;
	public InstruccionElements getInstruccionAccess() {
		return pInstruccion;
	}
	
	public ParserRule getInstruccionRule() {
		return getInstruccionAccess().getRule();
	}
	
	//Circulo:     'C' x=INT y=INT r=INT;
	public CirculoElements getCirculoAccess() {
		return pCirculo;
	}
	
	public ParserRule getCirculoRule() {
		return getCirculoAccess().getRule();
	}
	
	//Rectangulo:  'R' x1=INT y1=INT x2=INT y2=INT x3=INT y3=INT x4=INT y4=INT;
	public RectanguloElements getRectanguloAccess() {
		return pRectangulo;
	}
	
	public ParserRule getRectanguloRule() {
		return getRectanguloAccess().getRule();
	}
	
	//Linea:       'L' x1=INT y1=INT x2=INT y2=INT;
	public LineaElements getLineaAccess() {
		return pLinea;
	}
	
	public ParserRule getLineaRule() {
		return getLineaAccess().getRule();
	}
	
	//Texto:       'T' x=INT y=INT texto=STRING;
	public TextoElements getTextoAccess() {
		return pTexto;
	}
	
	public ParserRule getTextoRule() {
		return getTextoAccess().getRule();
	}
	
	//Punto:       'P' x=INT y=INT;
	public PuntoElements getPuntoAccess() {
		return pPunto;
	}
	
	public ParserRule getPuntoRule() {
		return getPuntoAccess().getRule();
	}
	
	//Color:       ('SC' | 'FC' | 'BG') color=HEXCOLOR;
	public ColorElements getColorAccess() {
		return pColor;
	}
	
	public ParserRule getColorRule() {
		return getColorAccess().getRule();
	}
	
	//Estilo:      'SW' valor=INT;
	public EstiloElements getEstiloAccess() {
		return pEstilo;
	}
	
	public ParserRule getEstiloRule() {
		return getEstiloAccess().getRule();
	}
	
	//Fuente:      'FS' valor=INT;
	public FuenteElements getFuenteAccess() {
		return pFuente;
	}
	
	public ParserRule getFuenteRule() {
		return getFuenteAccess().getRule();
	}
	
	//terminal HEXCOLOR: '#' ('A'..'F'|'a'..'f'|'0'..'9')+;
	public TerminalRule getHEXCOLORRule() {
		return tHEXCOLOR;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
