/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Circulo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Circulo#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Circulo#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Circulo#getR <em>R</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getCirculo()
 * @model
 * @generated
 */
public interface Circulo extends Instruccion
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getCirculo_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Circulo#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getCirculo_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Circulo#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' attribute.
   * @see #setR(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getCirculo_R()
   * @model
   * @generated
   */
  int getR();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Circulo#getR <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' attribute.
   * @see #getR()
   * @generated
   */
  void setR(int value);

} // Circulo
