/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Color#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getColor()
 * @model
 * @generated
 */
public interface Color extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see #setColor(String)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getColor_Color()
   * @model
   * @generated
   */
  String getColor();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Color#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see #getColor()
   * @generated
   */
  void setColor(String value);

} // Color
