/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Factory
 * @model kind="package"
 * @generated
 */
public interface Dibujos1Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dibujos1";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/dibujos1/Dibujos1";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dibujos1";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Dibujos1Package eINSTANCE = org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.ModeloImpl <em>Modelo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.ModeloImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getModelo()
   * @generated
   */
  int MODELO = 0;

  /**
   * The feature id for the '<em><b>Instrucciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODELO__INSTRUCCIONES = 0;

  /**
   * The number of structural features of the '<em>Modelo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODELO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.InstruccionImpl <em>Instruccion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.InstruccionImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getInstruccion()
   * @generated
   */
  int INSTRUCCION = 1;

  /**
   * The number of structural features of the '<em>Instruccion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.CirculoImpl <em>Circulo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.CirculoImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getCirculo()
   * @generated
   */
  int CIRCULO = 2;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIRCULO__X = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIRCULO__Y = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIRCULO__R = INSTRUCCION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Circulo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIRCULO_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl <em>Rectangulo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getRectangulo()
   * @generated
   */
  int RECTANGULO = 3;

  /**
   * The feature id for the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__X1 = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__Y1 = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__X2 = INSTRUCCION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Y2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__Y2 = INSTRUCCION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>X3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__X3 = INSTRUCCION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Y3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__Y3 = INSTRUCCION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>X4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__X4 = INSTRUCCION_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Y4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO__Y4 = INSTRUCCION_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Rectangulo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGULO_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.LineaImpl <em>Linea</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.LineaImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getLinea()
   * @generated
   */
  int LINEA = 4;

  /**
   * The feature id for the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEA__X1 = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEA__Y1 = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEA__X2 = INSTRUCCION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Y2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEA__Y2 = INSTRUCCION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Linea</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEA_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.TextoImpl <em>Texto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.TextoImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getTexto()
   * @generated
   */
  int TEXTO = 5;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTO__X = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTO__Y = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTO__TEXTO = INSTRUCCION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Texto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTO_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.PuntoImpl <em>Punto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.PuntoImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getPunto()
   * @generated
   */
  int PUNTO = 6;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUNTO__X = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUNTO__Y = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Punto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUNTO_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.ColorImpl <em>Color</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.ColorImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getColor()
   * @generated
   */
  int COLOR = 7;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__COLOR = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Color</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.EstiloImpl <em>Estilo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.EstiloImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getEstilo()
   * @generated
   */
  int ESTILO = 8;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO__VALOR = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Estilo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dibujos1.dibujos1.impl.FuenteImpl <em>Fuente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dibujos1.dibujos1.impl.FuenteImpl
   * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getFuente()
   * @generated
   */
  int FUENTE = 9;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUENTE__VALOR = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fuente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUENTE_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Modelo <em>Modelo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modelo</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Modelo
   * @generated
   */
  EClass getModelo();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dibujos1.dibujos1.Modelo#getInstrucciones <em>Instrucciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instrucciones</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Modelo#getInstrucciones()
   * @see #getModelo()
   * @generated
   */
  EReference getModelo_Instrucciones();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Instruccion <em>Instruccion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruccion</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Instruccion
   * @generated
   */
  EClass getInstruccion();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Circulo <em>Circulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Circulo</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Circulo
   * @generated
   */
  EClass getCirculo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Circulo#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Circulo#getX()
   * @see #getCirculo()
   * @generated
   */
  EAttribute getCirculo_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Circulo#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Circulo#getY()
   * @see #getCirculo()
   * @generated
   */
  EAttribute getCirculo_Y();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Circulo#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>R</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Circulo#getR()
   * @see #getCirculo()
   * @generated
   */
  EAttribute getCirculo_R();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo <em>Rectangulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rectangulo</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo
   * @generated
   */
  EClass getRectangulo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX1 <em>X1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X1</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getX1()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_X1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY1 <em>Y1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y1</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getY1()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_Y1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX2 <em>X2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X2</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getX2()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_X2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY2 <em>Y2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y2</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getY2()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_Y2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX3 <em>X3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X3</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getX3()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_X3();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY3 <em>Y3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y3</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getY3()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_Y3();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX4 <em>X4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X4</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getX4()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_X4();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY4 <em>Y4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y4</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Rectangulo#getY4()
   * @see #getRectangulo()
   * @generated
   */
  EAttribute getRectangulo_Y4();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Linea <em>Linea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Linea</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Linea
   * @generated
   */
  EClass getLinea();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Linea#getX1 <em>X1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X1</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Linea#getX1()
   * @see #getLinea()
   * @generated
   */
  EAttribute getLinea_X1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Linea#getY1 <em>Y1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y1</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Linea#getY1()
   * @see #getLinea()
   * @generated
   */
  EAttribute getLinea_Y1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Linea#getX2 <em>X2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X2</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Linea#getX2()
   * @see #getLinea()
   * @generated
   */
  EAttribute getLinea_X2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Linea#getY2 <em>Y2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y2</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Linea#getY2()
   * @see #getLinea()
   * @generated
   */
  EAttribute getLinea_Y2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Texto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Texto</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Texto
   * @generated
   */
  EClass getTexto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Texto#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Texto#getX()
   * @see #getTexto()
   * @generated
   */
  EAttribute getTexto_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Texto#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Texto#getY()
   * @see #getTexto()
   * @generated
   */
  EAttribute getTexto_Y();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Texto#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Texto#getTexto()
   * @see #getTexto()
   * @generated
   */
  EAttribute getTexto_Texto();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Punto <em>Punto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Punto</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Punto
   * @generated
   */
  EClass getPunto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Punto#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Punto#getX()
   * @see #getPunto()
   * @generated
   */
  EAttribute getPunto_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Punto#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Punto#getY()
   * @see #getPunto()
   * @generated
   */
  EAttribute getPunto_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Color
   * @generated
   */
  EClass getColor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Color#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Color#getColor()
   * @see #getColor()
   * @generated
   */
  EAttribute getColor_Color();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Estilo <em>Estilo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Estilo</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Estilo
   * @generated
   */
  EClass getEstilo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Estilo#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Estilo#getValor()
   * @see #getEstilo()
   * @generated
   */
  EAttribute getEstilo_Valor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dibujos1.dibujos1.Fuente <em>Fuente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fuente</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Fuente
   * @generated
   */
  EClass getFuente();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dibujos1.dibujos1.Fuente#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see org.xtext.example.dibujos1.dibujos1.Fuente#getValor()
   * @see #getFuente()
   * @generated
   */
  EAttribute getFuente_Valor();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Dibujos1Factory getDibujos1Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.ModeloImpl <em>Modelo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.ModeloImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getModelo()
     * @generated
     */
    EClass MODELO = eINSTANCE.getModelo();

    /**
     * The meta object literal for the '<em><b>Instrucciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODELO__INSTRUCCIONES = eINSTANCE.getModelo_Instrucciones();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.InstruccionImpl <em>Instruccion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.InstruccionImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getInstruccion()
     * @generated
     */
    EClass INSTRUCCION = eINSTANCE.getInstruccion();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.CirculoImpl <em>Circulo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.CirculoImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getCirculo()
     * @generated
     */
    EClass CIRCULO = eINSTANCE.getCirculo();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CIRCULO__X = eINSTANCE.getCirculo_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CIRCULO__Y = eINSTANCE.getCirculo_Y();

    /**
     * The meta object literal for the '<em><b>R</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CIRCULO__R = eINSTANCE.getCirculo_R();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl <em>Rectangulo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.RectanguloImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getRectangulo()
     * @generated
     */
    EClass RECTANGULO = eINSTANCE.getRectangulo();

    /**
     * The meta object literal for the '<em><b>X1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__X1 = eINSTANCE.getRectangulo_X1();

    /**
     * The meta object literal for the '<em><b>Y1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__Y1 = eINSTANCE.getRectangulo_Y1();

    /**
     * The meta object literal for the '<em><b>X2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__X2 = eINSTANCE.getRectangulo_X2();

    /**
     * The meta object literal for the '<em><b>Y2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__Y2 = eINSTANCE.getRectangulo_Y2();

    /**
     * The meta object literal for the '<em><b>X3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__X3 = eINSTANCE.getRectangulo_X3();

    /**
     * The meta object literal for the '<em><b>Y3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__Y3 = eINSTANCE.getRectangulo_Y3();

    /**
     * The meta object literal for the '<em><b>X4</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__X4 = eINSTANCE.getRectangulo_X4();

    /**
     * The meta object literal for the '<em><b>Y4</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGULO__Y4 = eINSTANCE.getRectangulo_Y4();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.LineaImpl <em>Linea</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.LineaImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getLinea()
     * @generated
     */
    EClass LINEA = eINSTANCE.getLinea();

    /**
     * The meta object literal for the '<em><b>X1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINEA__X1 = eINSTANCE.getLinea_X1();

    /**
     * The meta object literal for the '<em><b>Y1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINEA__Y1 = eINSTANCE.getLinea_Y1();

    /**
     * The meta object literal for the '<em><b>X2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINEA__X2 = eINSTANCE.getLinea_X2();

    /**
     * The meta object literal for the '<em><b>Y2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINEA__Y2 = eINSTANCE.getLinea_Y2();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.TextoImpl <em>Texto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.TextoImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getTexto()
     * @generated
     */
    EClass TEXTO = eINSTANCE.getTexto();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXTO__X = eINSTANCE.getTexto_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXTO__Y = eINSTANCE.getTexto_Y();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXTO__TEXTO = eINSTANCE.getTexto_Texto();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.PuntoImpl <em>Punto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.PuntoImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getPunto()
     * @generated
     */
    EClass PUNTO = eINSTANCE.getPunto();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUNTO__X = eINSTANCE.getPunto_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUNTO__Y = eINSTANCE.getPunto_Y();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.ColorImpl <em>Color</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.ColorImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getColor()
     * @generated
     */
    EClass COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR__COLOR = eINSTANCE.getColor_Color();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.EstiloImpl <em>Estilo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.EstiloImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getEstilo()
     * @generated
     */
    EClass ESTILO = eINSTANCE.getEstilo();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESTILO__VALOR = eINSTANCE.getEstilo_Valor();

    /**
     * The meta object literal for the '{@link org.xtext.example.dibujos1.dibujos1.impl.FuenteImpl <em>Fuente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dibujos1.dibujos1.impl.FuenteImpl
     * @see org.xtext.example.dibujos1.dibujos1.impl.Dibujos1PackageImpl#getFuente()
     * @generated
     */
    EClass FUENTE = eINSTANCE.getFuente();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUENTE__VALOR = eINSTANCE.getFuente_Valor();

  }

} //Dibujos1Package
