/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package
 * @generated
 */
public interface Dibujos1Factory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Dibujos1Factory eINSTANCE = org.xtext.example.dibujos1.dibujos1.impl.Dibujos1FactoryImpl.init();

  /**
   * Returns a new object of class '<em>Modelo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Modelo</em>'.
   * @generated
   */
  Modelo createModelo();

  /**
   * Returns a new object of class '<em>Instruccion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruccion</em>'.
   * @generated
   */
  Instruccion createInstruccion();

  /**
   * Returns a new object of class '<em>Circulo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Circulo</em>'.
   * @generated
   */
  Circulo createCirculo();

  /**
   * Returns a new object of class '<em>Rectangulo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rectangulo</em>'.
   * @generated
   */
  Rectangulo createRectangulo();

  /**
   * Returns a new object of class '<em>Linea</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Linea</em>'.
   * @generated
   */
  Linea createLinea();

  /**
   * Returns a new object of class '<em>Texto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Texto</em>'.
   * @generated
   */
  Texto createTexto();

  /**
   * Returns a new object of class '<em>Punto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Punto</em>'.
   * @generated
   */
  Punto createPunto();

  /**
   * Returns a new object of class '<em>Color</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color</em>'.
   * @generated
   */
  Color createColor();

  /**
   * Returns a new object of class '<em>Estilo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Estilo</em>'.
   * @generated
   */
  Estilo createEstilo();

  /**
   * Returns a new object of class '<em>Fuente</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fuente</em>'.
   * @generated
   */
  Fuente createFuente();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  Dibujos1Package getDibujos1Package();

} //Dibujos1Factory
