/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fuente</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Fuente#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getFuente()
 * @model
 * @generated
 */
public interface Fuente extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getFuente_Valor()
   * @model
   * @generated
   */
  int getValor();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Fuente#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(int value);

} // Fuente
