/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruccion</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getInstruccion()
 * @model
 * @generated
 */
public interface Instruccion extends EObject
{
} // Instruccion
