/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Linea</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Linea#getX1 <em>X1</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Linea#getY1 <em>Y1</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Linea#getX2 <em>X2</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Linea#getY2 <em>Y2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getLinea()
 * @model
 * @generated
 */
public interface Linea extends Instruccion
{
  /**
   * Returns the value of the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X1</em>' attribute.
   * @see #setX1(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getLinea_X1()
   * @model
   * @generated
   */
  int getX1();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Linea#getX1 <em>X1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X1</em>' attribute.
   * @see #getX1()
   * @generated
   */
  void setX1(int value);

  /**
   * Returns the value of the '<em><b>Y1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y1</em>' attribute.
   * @see #setY1(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getLinea_Y1()
   * @model
   * @generated
   */
  int getY1();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Linea#getY1 <em>Y1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y1</em>' attribute.
   * @see #getY1()
   * @generated
   */
  void setY1(int value);

  /**
   * Returns the value of the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X2</em>' attribute.
   * @see #setX2(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getLinea_X2()
   * @model
   * @generated
   */
  int getX2();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Linea#getX2 <em>X2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X2</em>' attribute.
   * @see #getX2()
   * @generated
   */
  void setX2(int value);

  /**
   * Returns the value of the '<em><b>Y2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y2</em>' attribute.
   * @see #setY2(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getLinea_Y2()
   * @model
   * @generated
   */
  int getY2();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Linea#getY2 <em>Y2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y2</em>' attribute.
   * @see #getY2()
   * @generated
   */
  void setY2(int value);

} // Linea
