/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modelo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Modelo#getInstrucciones <em>Instrucciones</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getModelo()
 * @model
 * @generated
 */
public interface Modelo extends EObject
{
  /**
   * Returns the value of the '<em><b>Instrucciones</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dibujos1.dibujos1.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instrucciones</em>' containment reference list.
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getModelo_Instrucciones()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstrucciones();

} // Modelo
