/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rectangulo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX1 <em>X1</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY1 <em>Y1</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX2 <em>X2</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY2 <em>Y2</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX3 <em>X3</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY3 <em>Y3</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX4 <em>X4</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY4 <em>Y4</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo()
 * @model
 * @generated
 */
public interface Rectangulo extends Instruccion
{
  /**
   * Returns the value of the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X1</em>' attribute.
   * @see #setX1(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_X1()
   * @model
   * @generated
   */
  int getX1();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX1 <em>X1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X1</em>' attribute.
   * @see #getX1()
   * @generated
   */
  void setX1(int value);

  /**
   * Returns the value of the '<em><b>Y1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y1</em>' attribute.
   * @see #setY1(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_Y1()
   * @model
   * @generated
   */
  int getY1();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY1 <em>Y1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y1</em>' attribute.
   * @see #getY1()
   * @generated
   */
  void setY1(int value);

  /**
   * Returns the value of the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X2</em>' attribute.
   * @see #setX2(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_X2()
   * @model
   * @generated
   */
  int getX2();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX2 <em>X2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X2</em>' attribute.
   * @see #getX2()
   * @generated
   */
  void setX2(int value);

  /**
   * Returns the value of the '<em><b>Y2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y2</em>' attribute.
   * @see #setY2(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_Y2()
   * @model
   * @generated
   */
  int getY2();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY2 <em>Y2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y2</em>' attribute.
   * @see #getY2()
   * @generated
   */
  void setY2(int value);

  /**
   * Returns the value of the '<em><b>X3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X3</em>' attribute.
   * @see #setX3(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_X3()
   * @model
   * @generated
   */
  int getX3();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX3 <em>X3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X3</em>' attribute.
   * @see #getX3()
   * @generated
   */
  void setX3(int value);

  /**
   * Returns the value of the '<em><b>Y3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y3</em>' attribute.
   * @see #setY3(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_Y3()
   * @model
   * @generated
   */
  int getY3();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY3 <em>Y3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y3</em>' attribute.
   * @see #getY3()
   * @generated
   */
  void setY3(int value);

  /**
   * Returns the value of the '<em><b>X4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X4</em>' attribute.
   * @see #setX4(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_X4()
   * @model
   * @generated
   */
  int getX4();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getX4 <em>X4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X4</em>' attribute.
   * @see #getX4()
   * @generated
   */
  void setX4(int value);

  /**
   * Returns the value of the '<em><b>Y4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y4</em>' attribute.
   * @see #setY4(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getRectangulo_Y4()
   * @model
   * @generated
   */
  int getY4();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Rectangulo#getY4 <em>Y4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y4</em>' attribute.
   * @see #getY4()
   * @generated
   */
  void setY4(int value);

} // Rectangulo
