/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Texto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Texto#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Texto#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.example.dibujos1.dibujos1.Texto#getTexto <em>Texto</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getTexto()
 * @model
 * @generated
 */
public interface Texto extends Instruccion
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getTexto_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Texto#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getTexto_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Texto#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texto</em>' attribute.
   * @see #setTexto(String)
   * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package#getTexto_Texto()
   * @model
   * @generated
   */
  String getTexto();

  /**
   * Sets the value of the '{@link org.xtext.example.dibujos1.dibujos1.Texto#getTexto <em>Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texto</em>' attribute.
   * @see #getTexto()
   * @generated
   */
  void setTexto(String value);

} // Texto
