/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Dibujos1AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/dibujos1/parser/antlr/internal/InternalDibujos1.tokens");
	}
}
