/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.dibujos1.parser.antlr.internal.InternalDibujos1Parser;
import org.xtext.example.dibujos1.services.Dibujos1GrammarAccess;

public class Dibujos1Parser extends AbstractAntlrParser {

	@Inject
	private Dibujos1GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDibujos1Parser createParser(XtextTokenStream stream) {
		return new InternalDibujos1Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Modelo";
	}

	public Dibujos1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Dibujos1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
