/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDibujos1ScopeProvider extends DelegatingScopeProvider {
}
