/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.dibujos1.dibujos1.Circulo;
import org.xtext.example.dibujos1.dibujos1.Color;
import org.xtext.example.dibujos1.dibujos1.Dibujos1Package;
import org.xtext.example.dibujos1.dibujos1.Estilo;
import org.xtext.example.dibujos1.dibujos1.Fuente;
import org.xtext.example.dibujos1.dibujos1.Linea;
import org.xtext.example.dibujos1.dibujos1.Modelo;
import org.xtext.example.dibujos1.dibujos1.Punto;
import org.xtext.example.dibujos1.dibujos1.Rectangulo;
import org.xtext.example.dibujos1.dibujos1.Texto;
import org.xtext.example.dibujos1.services.Dibujos1GrammarAccess;

@SuppressWarnings("all")
public class Dibujos1SemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private Dibujos1GrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == Dibujos1Package.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case Dibujos1Package.CIRCULO:
				sequence_Circulo(context, (Circulo) semanticObject); 
				return; 
			case Dibujos1Package.COLOR:
				sequence_Color(context, (Color) semanticObject); 
				return; 
			case Dibujos1Package.ESTILO:
				sequence_Estilo(context, (Estilo) semanticObject); 
				return; 
			case Dibujos1Package.FUENTE:
				sequence_Fuente(context, (Fuente) semanticObject); 
				return; 
			case Dibujos1Package.LINEA:
				sequence_Linea(context, (Linea) semanticObject); 
				return; 
			case Dibujos1Package.MODELO:
				sequence_Modelo(context, (Modelo) semanticObject); 
				return; 
			case Dibujos1Package.PUNTO:
				sequence_Punto(context, (Punto) semanticObject); 
				return; 
			case Dibujos1Package.RECTANGULO:
				sequence_Rectangulo(context, (Rectangulo) semanticObject); 
				return; 
			case Dibujos1Package.TEXTO:
				sequence_Texto(context, (Texto) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Circulo
	 *     Circulo returns Circulo
	 *
	 * Constraint:
	 *     (x=INT y=INT r=INT)
	 * </pre>
	 */
	protected void sequence_Circulo(ISerializationContext context, Circulo semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.CIRCULO__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.CIRCULO__X));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.CIRCULO__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.CIRCULO__Y));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.CIRCULO__R) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.CIRCULO__R));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCirculoAccess().getXINTTerminalRuleCall_1_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getCirculoAccess().getYINTTerminalRuleCall_2_0(), semanticObject.getY());
		feeder.accept(grammarAccess.getCirculoAccess().getRINTTerminalRuleCall_3_0(), semanticObject.getR());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Color
	 *     Color returns Color
	 *
	 * Constraint:
	 *     color=HEXCOLOR
	 * </pre>
	 */
	protected void sequence_Color(ISerializationContext context, Color semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.COLOR__COLOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.COLOR__COLOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColorAccess().getColorHEXCOLORTerminalRuleCall_1_0(), semanticObject.getColor());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Estilo
	 *     Estilo returns Estilo
	 *
	 * Constraint:
	 *     valor=INT
	 * </pre>
	 */
	protected void sequence_Estilo(ISerializationContext context, Estilo semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.ESTILO__VALOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.ESTILO__VALOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEstiloAccess().getValorINTTerminalRuleCall_1_0(), semanticObject.getValor());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Fuente
	 *     Fuente returns Fuente
	 *
	 * Constraint:
	 *     valor=INT
	 * </pre>
	 */
	protected void sequence_Fuente(ISerializationContext context, Fuente semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.FUENTE__VALOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.FUENTE__VALOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFuenteAccess().getValorINTTerminalRuleCall_1_0(), semanticObject.getValor());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Linea
	 *     Linea returns Linea
	 *
	 * Constraint:
	 *     (x1=INT y1=INT x2=INT y2=INT)
	 * </pre>
	 */
	protected void sequence_Linea(ISerializationContext context, Linea semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.LINEA__X1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.LINEA__X1));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.LINEA__Y1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.LINEA__Y1));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.LINEA__X2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.LINEA__X2));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.LINEA__Y2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.LINEA__Y2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLineaAccess().getX1INTTerminalRuleCall_1_0(), semanticObject.getX1());
		feeder.accept(grammarAccess.getLineaAccess().getY1INTTerminalRuleCall_2_0(), semanticObject.getY1());
		feeder.accept(grammarAccess.getLineaAccess().getX2INTTerminalRuleCall_3_0(), semanticObject.getX2());
		feeder.accept(grammarAccess.getLineaAccess().getY2INTTerminalRuleCall_4_0(), semanticObject.getY2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Modelo returns Modelo
	 *
	 * Constraint:
	 *     instrucciones+=Instruccion+
	 * </pre>
	 */
	protected void sequence_Modelo(ISerializationContext context, Modelo semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Punto
	 *     Punto returns Punto
	 *
	 * Constraint:
	 *     (x=INT y=INT)
	 * </pre>
	 */
	protected void sequence_Punto(ISerializationContext context, Punto semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.PUNTO__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.PUNTO__X));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.PUNTO__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.PUNTO__Y));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPuntoAccess().getXINTTerminalRuleCall_1_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getPuntoAccess().getYINTTerminalRuleCall_2_0(), semanticObject.getY());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Rectangulo
	 *     Rectangulo returns Rectangulo
	 *
	 * Constraint:
	 *     (
	 *         x1=INT 
	 *         y1=INT 
	 *         x2=INT 
	 *         y2=INT 
	 *         x3=INT 
	 *         y3=INT 
	 *         x4=INT 
	 *         y4=INT
	 *     )
	 * </pre>
	 */
	protected void sequence_Rectangulo(ISerializationContext context, Rectangulo semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__X1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__X1));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y1));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__X2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__X2));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y2));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__X3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__X3));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y3));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__X4) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__X4));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y4) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.RECTANGULO__Y4));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRectanguloAccess().getX1INTTerminalRuleCall_1_0(), semanticObject.getX1());
		feeder.accept(grammarAccess.getRectanguloAccess().getY1INTTerminalRuleCall_2_0(), semanticObject.getY1());
		feeder.accept(grammarAccess.getRectanguloAccess().getX2INTTerminalRuleCall_3_0(), semanticObject.getX2());
		feeder.accept(grammarAccess.getRectanguloAccess().getY2INTTerminalRuleCall_4_0(), semanticObject.getY2());
		feeder.accept(grammarAccess.getRectanguloAccess().getX3INTTerminalRuleCall_5_0(), semanticObject.getX3());
		feeder.accept(grammarAccess.getRectanguloAccess().getY3INTTerminalRuleCall_6_0(), semanticObject.getY3());
		feeder.accept(grammarAccess.getRectanguloAccess().getX4INTTerminalRuleCall_7_0(), semanticObject.getX4());
		feeder.accept(grammarAccess.getRectanguloAccess().getY4INTTerminalRuleCall_8_0(), semanticObject.getY4());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruccion returns Texto
	 *     Texto returns Texto
	 *
	 * Constraint:
	 *     (x=INT y=INT texto=STRING)
	 * </pre>
	 */
	protected void sequence_Texto(ISerializationContext context, Texto semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.TEXTO__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.TEXTO__X));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.TEXTO__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.TEXTO__Y));
			if (transientValues.isValueTransient(semanticObject, Dibujos1Package.Literals.TEXTO__TEXTO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Dibujos1Package.Literals.TEXTO__TEXTO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTextoAccess().getXINTTerminalRuleCall_1_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getTextoAccess().getYINTTerminalRuleCall_2_0(), semanticObject.getY());
		feeder.accept(grammarAccess.getTextoAccess().getTextoSTRINGTerminalRuleCall_3_0(), semanticObject.getTexto());
		feeder.finish();
	}
	
	
}
