/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.dibujos1.services.Dibujos1GrammarAccess;

@SuppressWarnings("all")
public class Dibujos1SyntacticSequencer extends AbstractSyntacticSequencer {

	protected Dibujos1GrammarAccess grammarAccess;
	protected AbstractElementAlias match_Color_BGKeyword_0_2_or_FCKeyword_0_1_or_SCKeyword_0_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (Dibujos1GrammarAccess) access;
		match_Color_BGKeyword_0_2_or_FCKeyword_0_1_or_SCKeyword_0_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getColorAccess().getBGKeyword_0_2()), new TokenAlias(false, false, grammarAccess.getColorAccess().getFCKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getColorAccess().getSCKeyword_0_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Color_BGKeyword_0_2_or_FCKeyword_0_1_or_SCKeyword_0_0.equals(syntax))
				emit_Color_BGKeyword_0_2_or_FCKeyword_0_1_or_SCKeyword_0_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'SC' | 'FC' | 'BG'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) color=HEXCOLOR
	 
	 * </pre>
	 */
	protected void emit_Color_BGKeyword_0_2_or_FCKeyword_0_1_or_SCKeyword_0_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
