/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.dibujos1.dibujos1.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.example.dibujos1.dibujos1.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.example.dibujos1.dibujos1.Dibujos1Package
 * @generated
 */
public class Dibujos1Switch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static Dibujos1Package modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Dibujos1Switch()
  {
    if (modelPackage == null)
    {
      modelPackage = Dibujos1Package.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case Dibujos1Package.MODELO:
      {
        Modelo modelo = (Modelo)theEObject;
        T result = caseModelo(modelo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.INSTRUCCION:
      {
        Instruccion instruccion = (Instruccion)theEObject;
        T result = caseInstruccion(instruccion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.CIRCULO:
      {
        Circulo circulo = (Circulo)theEObject;
        T result = caseCirculo(circulo);
        if (result == null) result = caseInstruccion(circulo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.RECTANGULO:
      {
        Rectangulo rectangulo = (Rectangulo)theEObject;
        T result = caseRectangulo(rectangulo);
        if (result == null) result = caseInstruccion(rectangulo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.LINEA:
      {
        Linea linea = (Linea)theEObject;
        T result = caseLinea(linea);
        if (result == null) result = caseInstruccion(linea);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.TEXTO:
      {
        Texto texto = (Texto)theEObject;
        T result = caseTexto(texto);
        if (result == null) result = caseInstruccion(texto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.PUNTO:
      {
        Punto punto = (Punto)theEObject;
        T result = casePunto(punto);
        if (result == null) result = caseInstruccion(punto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.COLOR:
      {
        Color color = (Color)theEObject;
        T result = caseColor(color);
        if (result == null) result = caseInstruccion(color);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.ESTILO:
      {
        Estilo estilo = (Estilo)theEObject;
        T result = caseEstilo(estilo);
        if (result == null) result = caseInstruccion(estilo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Dibujos1Package.FUENTE:
      {
        Fuente fuente = (Fuente)theEObject;
        T result = caseFuente(fuente);
        if (result == null) result = caseInstruccion(fuente);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Modelo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Modelo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseModelo(Modelo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Instruccion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Instruccion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInstruccion(Instruccion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Circulo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Circulo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCirculo(Circulo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Rectangulo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Rectangulo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRectangulo(Rectangulo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Linea</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Linea</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLinea(Linea object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Texto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Texto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTexto(Texto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Punto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Punto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePunto(Punto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Color</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Color</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseColor(Color object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Estilo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Estilo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEstilo(Estilo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Fuente</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Fuente</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFuente(Fuente object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //Dibujos1Switch
